# version: '3.8'

name: robin

networks:
  database:
    driver: bridge
    name: database
      
services:
  redis:
    image: redis 
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - database
    volumes:
      - redis:/data
    healthcheck:
      test: redis-cli ping
      interval: 3s
      timeout: 1s
      retries: 5

  clickhouse:
    build: clickhouse 
    container_name: clickhouse
    restart: always
    environment:
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: password123
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: '1'
    volumes:
      - clickhouse:/var/lib/clickhouse
      - ~/docker/copy_to_clickhouse:/var/lib/clickhouse/copyed
    ports:
      - 8123:8123
      - 9000:9000
    networks:
      - database
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1
      interval: 3s
      timeout: 1s
      retries: 5

  robin:
    # dns:
    #   - 8.8.8.8
    #   - 8.8.4.4
    env_file:
      - ../.env
    environment:
      - PROJECT_NAME=${PROJECT_NAME}
      - PROJECT_VERSION=${PROJECT_VERSION}
      - PORT=${PORT}
    build:
      context: ../
      dockerfile: deploy/robin/Dockerfile
      no_cache: true
      args:
        - PROJECT_NAME
        - PROJECT_VERSION
        - PORT

    # image: robin
    container_name: robin
    restart: always
    volumes:
      - ~/docker/configs/Robin:/Robin/config
      - ~/docker/logs/Robin:/Robin/log
    ports:
      - 8008:8008
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - database
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8008/ping || exit 1
      interval: 3s
      timeout: 1s
      retries: 5
    depends_on:
      clickhouse:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  clickhouse:
    external: true
  redis:
    external: true