info:
  contact: {}
paths:
  /api/info/:
    get:
      description: Возвращает информацию о приложении
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: Полчить информацию
      tags:
      - System
  /api/log/:
    get:
      description: Возвращает логи приложения в text/json и других зарегистрированных
        форматах
      parameters:
      - description: Формат вывода (text, str, raw, json, xml, html, grafana)
        in: query
        name: format
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Получить лог
      tags:
      - System
  /api/log/clear/:
    delete:
      description: Очищает файл логов приложения
      produces:
      - text/plain
      responses:
        "200":
          description: Логи очищены
          schema:
            type: string
        "500":
          description: Ошибка при очистке логов
          schema:
            type: string
      summary: Очистить лог
      tags:
      - System
    post:
      description: Очищает файл логов приложения
      produces:
      - text/plain
      responses:
        "200":
          description: Логи очищены
          schema:
            type: string
        "500":
          description: Ошибка при очистке логов
          schema:
            type: string
      summary: Очистить лог
      tags:
      - System
  /api/reload/:
    post:
      description: Перечитывает config/Robin.json и переинициализирует активные БД
        и кэш. Требует admin token
      parameters:
      - description: Admin token
        in: header
        name: X-Admin-Token
        type: string
      - description: Bearer admin token
        in: header
        name: Authorization
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
        "403":
          description: Forbidden
          schema:
            type: string
        "405":
          description: Method Not Allowed
          schema:
            type: string
      summary: Перезагрузить конфигурационный файл
      tags:
      - System
  /get/tag/:
    get:
      description: Возвращает значение тега на выбранную дату.
      parameters:
      - description: Наименование тега
        in: query
        name: tag
        required: true
        type: string
      - description: Дата
        in: query
        name: date
        type: string
      - description: Дата начала периода
        in: query
        name: from
        type: string
      - description: Дата окончания периода
        in: query
        name: to
        type: string
      - description: Функция группировки (avg, sum, count, min, max)
        in: query
        name: group
        type: string
      - description: Количество значений
        in: query
        name: count
        type: string
      - description: Округление, знаков после запятой (по умолчанию 2)
        in: query
        name: round
        type: string
      - description: Формат вывода (str - по умолчанию, json, raw)
        in: query
        name: format
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: Получить значение тега
      tags:
      - Tag
  /get/tag/down/:
    get:
      description: Возвращает дату и время отключения оборудования
      parameters:
      - description: Наименование тега
        in: query
        name: tag
        required: true
        type: string
      - description: Дата начала периода
        in: query
        name: from
        type: string
      - description: Дата окончания периода
        in: query
        name: to
        type: string
      - description: Номер отключения после даты начала (0 - первое отключение)
        in: query
        name: count
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: Получить даты отключения оборудования
      tags:
      - Tag
  /get/tag/list/:
    get:
      description: Возвращает список всех тегов по маске
      parameters:
      - description: Маска поиска
        in: query
        name: like
        type: string
      - description: Формат вывода (str - по умолчанию, json, raw)
        in: query
        name: format
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: Получить список тегов
      tags:
      - Tag
  /get/tag/up/:
    get:
      description: Возвращает дату и время включения оборудования
      parameters:
      - description: Наименование тега
        in: query
        name: tag
        required: true
        type: string
      - description: Дата начала периода
        in: query
        name: from
        type: string
      - description: Дата окончания периода
        in: query
        name: to
        type: string
      - description: Номер включения после даты начала (0 - первое включение)
        in: query
        name: count
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: Получить даты включения оборудования
      tags:
      - Tag
  /tag/decode/:
    get:
      description: Возвращает расшифровку имени тега
      parameters:
      - description: Наименование тега
        in: query
        name: tag
        required: true
        type: string
      - description: Формат вывода (str - по умолчанию, json, raw)
        in: query
        name: format
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: Получить расшифровку имени тега
      tags:
      - Tag
  /templ/add/:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Добавляет шаблон. Требует admin token
      parameters:
      - description: Admin token
        in: header
        name: X-Admin-Token
        type: string
      - description: Bearer admin token
        in: header
        name: Authorization
        type: string
      - description: Имя шаблона
        in: formData
        name: name
        required: true
        type: string
      - description: Тело шаблона
        in: formData
        name: body
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "403":
          description: Forbidden
          schema:
            type: string
        "405":
          description: Method Not Allowed
          schema:
            type: string
      summary: Добавить шаблон
      tags:
      - Template
  /templ/delete/:
    delete:
      description: Удаляет шаблон. Требует admin token
      parameters:
      - description: Admin token
        in: header
        name: X-Admin-Token
        type: string
      - description: Bearer admin token
        in: header
        name: Authorization
        type: string
      - description: Имя шаблона
        in: query
        name: name
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "403":
          description: Forbidden
          schema:
            type: string
        "405":
          description: Method Not Allowed
          schema:
            type: string
      summary: Удалить шаблон
      tags:
      - Template
  /templ/edit/:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Изменяет тело шаблона. Требует admin token
      parameters:
      - description: Admin token
        in: header
        name: X-Admin-Token
        type: string
      - description: Bearer admin token
        in: header
        name: Authorization
        type: string
      - description: Имя шаблона
        in: formData
        name: name
        required: true
        type: string
      - description: Тело шаблона
        in: formData
        name: body
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "403":
          description: Forbidden
          schema:
            type: string
        "405":
          description: Method Not Allowed
          schema:
            type: string
      summary: Изменить тело шаблона
      tags:
      - Template
  /templ/exec/:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Выполняет шаблон. Требует admin token
      parameters:
      - description: Admin token
        in: header
        name: X-Admin-Token
        type: string
      - description: Bearer admin token
        in: header
        name: Authorization
        type: string
      - description: Имя шаблона
        in: formData
        name: name
        required: true
        type: string
      - description: Имя базы данных
        in: formData
        name: db
        type: string
      - description: Формат вывода (text, str, raw, json, xml, html, grafana)
        in: formData
        name: format
        type: string
      - description: Список аргументов k1=v1,k2=v2
        in: formData
        name: args
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "403":
          description: Forbidden
          schema:
            type: string
        "405":
          description: Method Not Allowed
          schema:
            type: string
      summary: Выполнить шаблон
      tags:
      - Template
      x-try-it-out-enabled: false
  /templ/get/:
    get:
      description: Возвращает тело шаблона. Требует admin token
      parameters:
      - description: Admin token
        in: header
        name: X-Admin-Token
        type: string
      - description: Bearer admin token
        in: header
        name: Authorization
        type: string
      - description: Имя шаблона
        in: query
        name: name
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "403":
          description: Forbidden
          schema:
            type: string
      summary: Получить тело шаблона
      tags:
      - Template
  /templ/list/:
    get:
      description: Возвращает список шаблонов. Требует admin token
      parameters:
      - description: Admin token
        in: header
        name: X-Admin-Token
        type: string
      - description: Bearer admin token
        in: header
        name: Authorization
        type: string
      - description: Маска поиска шаблона
        in: query
        name: like
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "403":
          description: Forbidden
          schema:
            type: string
      summary: Получить список шаблонов
      tags:
      - Template
swagger: "2.0"
